### ISSUE TITLE
USB compatibility with STM32F103

### ISSUE THREAD

**Issue by profdc9** [IOsetting/StdPeriphLib_CH32F1#1]
I am not sure if you were able to read the Chinese manual for the CH32F103, but there have been problems that many users of the Bluepill have with getting USB to work.  If you could answer some questions for me it would help me investigate this.

1.  First, what is the Coreid that the CH32F103 presents when debugging?  The STM32F1 is 0x1BA01477, for example.
2.  Does the datasheet say that 22 ohm resistors should be in series with the PA11/PA12 USB -/+ pins and that PA12 should be pulled up with a 1k5?  The schematic on the evaluation board does not include these.  Most Bluepills do include these, and I am wondering if that's part of the problem.
3. Is the USB device on the CH32F103 intended to be register and memory compatible with STM32F103 ?  The registers have the same names and bits, but there could be additional initialization required for the CH32F103 that is not required on the STM32F103.
4. Are there any complete code examples of USB for the CH32F103, for example, a USB CDC implementation that you know of?

Thank you!

**Comment by IOsetting** [comment]
1. 0x2ba01477
1. I am not sure, but 22R resistors should not be a problem. CH32F103 series have built-in pull-up resistors, if 1.5k pull up is connected, in the code don't set the pin to PULLUP again. 
1. Yes, they should be the same. Their tech support recommended to clear all registers' status in the init step, please refer to this [post](https://www.wch.cn/bbs/thread-85251-1.html#9) (you can translate it in Chrome)
1. I have asked them for cdc code example, just wait for their reply.

**Comment by IOsetting** [comment]
Please download the example code from [WCH website](https://www.wch.cn/downloads/CH32F103EVT_ZIP.html). USB CDC implementation example is under folder /EVT/EXAM/USB/USBD/SimulateCDC/

**Comment by profdc9** [comment]
Thanks for the help.  I'll give the instructions a try and see if that fixes the USB drivers I am trying to port.
